### ISSUE TITLE
Statusbar and line indicator coloring off

### ISSUE THREAD

**Issue by dcallea** [bluz71/vim-moonfly-colors#12]
![screenshot](https://user-images.githubusercontent.com/36043289/107863046-6d4b7480-6e51-11eb-8b55-3dc78ccfe891.png)

I've configured my .vimrc as per instructions in the documentation but the statusbar background coloring seems off. This is both with lightline and the native status bar.
My line indicator also does not get highlighted as shown in this screenshot: https://raw.githubusercontent.com/bluz71/misc-binaries/master/moonfly/ruby_moonfly.png
Is it supposed to look this way, a bug, or a misconfiguration on my part?

**Comment by bluz71** [comment]
The moonfly Lightline statusline is designed to look like that.

I designed it to mimic my [moonfly-statusline](https://github.com/bluz71/vim-moonfly-statusline) statusline as seen here:

![moonfly](https://user-images.githubusercontent.com/11382509/107866635-04064880-6ec7-11eb-8bd0-d86a70b8a266.png)

All is as intended. Whether one likes the look will vary from person to person.

Best regards.

**Comment by dcallea** [comment]
My bad, it looked off for my eyes when compared with the vertical bar on the right.
Do you might have a guess on what causes the line indicator on the left to not highlight like it does on your screenshot?

**Comment by bluz71** [comment]
> My line indicator also does not get highlighted as shown in this screenshot: https://raw.githubusercontent.com/bluz71/misc-binaries/master/moonfly/ruby_moonfly.png

The line indicator I believe is a Vim change, in my experience.

Do you use Vim or Neovim?

**Comment by bluz71** [comment]
> My bad, it looked off for my eyes when compared with the vertical bar on the right.

That vertical bar is the color column indicator. That is separate from status bar.

**Comment by dcallea** [comment]
> Do you use Vim or Neovim?
I use Vim.

**Comment by bluz71** [comment]
> I use Vim.

I suspected so. Vim changed things a year or so ago. I use Neovim and that does not have that issue.

I think you need to do something like this:

```viml
set relativenumber
if exists('&cursorlineopt')
    set cursorlineopt=number
    set cursorline
endif
```

**Comment by dcallea** [comment]
> > I use Vim.
> 
> I suspected so. Vim changed things a year or so ago. I use Neovim and that does not have that issue.
> 
> I think you need to do something like this:
> 
> ```viml
> set relativenumber
> if exists('&cursorlineopt')
>     set cursorlineopt=number
>     set cursorline
> endif
> ```

That works perfectly, thank you.
I appreciate all the work you put into your colorschemes (theming etc.) they really are some of the best available and thought out ones.

**Comment by bluz71** [comment]
Thank you, I appreciate that.

Hopefully your setup works a little better now.

Cheers.
