### ISSUE TITLE
Alternate gray color

### ISSUE THREAD

**Issue by lokesh-krishna** [bluz71/vim-moonfly-colors#17]
Hey, just discovered this colorscheme a few days ago and am completely in love with it. I'm trying to theme my entire system to this coloscheme and the only thing I am missing is a black/gray color that lies between `080808` and `323437`. What in your opinion would be a nice color between the two that would keep with the aesthetic of this colorscheme? 

I am basically looking for a color that can be used for the left half of the statusbar and the present one is too light creating too much of a difference between the two halves while I would like something that is not that light. Would really appreciate your suggestions in this regard. 

Thanks for creating this absolutely gorgeous colorscheme!

![swappy-20210816_092809](https://user-images.githubusercontent.com/20235646/129511335-c09e685b-5e01-46f3-b18e-0eb5608343d4.png)

**Comment by bluz71** [comment]
Hello,

Did you try one of these existing moonfly colors:

- `#303030`
- `#262626`
- `#1c1c1c`

**Comment by lokesh-krishna** [comment]
Oh my, I didn't know there were more colors available at all. Where can one view the full palette? I have been looking at the list at the very bottom of the repo.

**Comment by bluz71** [comment]
Inside the Vim colorscheme file, view the colors [here](https://github.com/bluz71/vim-moonfly-colors/blob/master/colors/moonfly.vim#L43).

**Comment by bluz71** [comment]
The colors in the README are with respect to terminal colors.

The full set of moonfly colors is in the Vim colorscheme.

Best of luck with regard to tweaking your desktop.
