### ISSUE TITLE
Diff looks bad with transparent background

### ISSUE THREAD

**Issue by frei-0xff** [bluz71/vim-moonfly-colors#20]
DiffAdd and DiffText highlight groups have unreadable foreground text color with g:moonflyTransparent activated.

![moonfly-colors-issue](https://user-images.githubusercontent.com/2990839/133913073-78b72051-6771-48f8-b244-c9722b279aaa.png)

**Comment by bluz71** [comment]
Just committed a fix that should resolve this issue.
