### ISSUE TITLE
Currently opened file in NvimTree is not highlighted

### ISSUE THREAD

**Issue by teenjuna** [bluz71/vim-moonfly-colors#25]
Example image:
<img width="937" alt="image" src="https://user-images.githubusercontent.com/53595243/182919857-73e63780-5e39-428c-832c-f18f1878351b.png">

As I understand, `NvimTreeCursorLine` is the related highlight group, but I can't override it. Perhaps you can help?

**Comment by teenjuna** [comment]
To be precise, something like this is desired:
![image](https://user-images.githubusercontent.com/53595243/182920362-4af31eae-40da-4026-a2b2-37de6412e40d.png)

**Comment by teenjuna** [comment]
Okay, actually I just forgot to enable `cursorline`. That's stupid

**Comment by bluz71** [comment]
Glad to hear their was an easy solution.

Cheers.
