### ISSUE TITLE
Hard to distinguish highlighting for Rust code

### ISSUE THREAD

**Issue by 112RG** [bluz71/vim-moonfly-colors#26]
Thank you for this awesome theme. But I am not sure if the issue I am having here is the themes fault or me configuring something wrong in Neovim. Shown on lines 21, 22, and some others. The color of tracing_subscriber and registry is near the same. I was wondering if this is something I have misconfigured or something I need to change

![image](https://i.imgur.com/kwcb8IG.png)

My neovim can be found here too https://github.com/112RG/dotfiles

**Comment by bluz71** [comment]
Namespaces are coloured blue.
Functions are in sky-blue.

This is a theme choice. There is no configuration issue by you.

In your case, I suggest overriding the `TSNamespace` highlight group with your preferred color.

Cheers.

**Comment by bluz71** [comment]
Ok, after spending some time thinking and experimenting, I do agree that namespaces and functions were not distinguishable enough.

I've now changed namespaces to turquoise / cyan; which is similar to what [NightFox](https://github.com/EdenEast/nightfox.nvim) does.

I appreciate the feedback. Hopefully this change works well for you.

Cheers.
