### ISSUE TITLE
Gnome terminal support

### ISSUE THREAD

**Issue by chhschou** [bluz71/vim-moonfly-colors#3]
Hi @bluz71 I made a gnome terminal script for setting up Moonfly colors. Please let me know if you are interested to include this in this repo, cheers.

**Comment by bluz71** [comment]
Yes, I would like to have a look at it. I already ship an iTerm2 moonfly color scheme for Mac users.

Gnome Terminal is likely the most used Linux Terminal. So it would be handy to have an easy option for such users.

So it is a command-line script, not a color-scheme you import in Gnome Terminal preference? Last time I looked Gnome Terminal did not have an option to import color schemes (at least on my Linux Mint box).

Thanks.

**Comment by bluz71** [comment]
@chhschou,

I am interested in your Gnome Terminal script. Either create a pull-request or just attach it to this issue.

Cheers.

**Comment by bluz71** [comment]
Merged and documented. Many thanks.
