### ISSUE TITLE
[feature request] bold highlights

### ISSUE THREAD

**Issue by arabindadora** [bluz71/vim-moonfly-colors#30]
I recently discovered this theme and totally love it. However, I miss the treesitter/lsp powered bold highlights for different objects like function names. Would it be possible to have that feature please - maybe behind an option flag?

**Comment by bluz71** [comment]
The moonfly colorscheme was always designed as a sans-bold theme; that is my particular design aesthetic. For better or worse, I am against bolding.

Unfortunately, that does mean that there will be no switch for bolding certain highlight groups.

However, if you do like the colorscheme, you can fork the project and add bold to the relevant highlight groups yourself.

Sorry that I couldn't be more helpful.

Best regards.

**Comment by bluz71** [comment]
Just a quick tip, you can use `autocmd`s to overwrite highlight groups with your preferred style. You don't need to fork the repository.

For example to embolden functions you can simply do this in your Neovim Lua configuration (e.g `init.lua`):

```lua
local augroup = vim.api.nvim_create_augroup
local autocmd = vim.api.nvim_create_autocmd
local highlight = vim.api.nvim_set_hl

local custom_events = augroup("CustomEvents", {})

autocmd("ColorScheme", {
  pattern = "moonfly",
  callback = function()
    highlight(0, "Function", { fg = "#74b2ff", bold = true })   
  end,
  group = custom_events,
})
```

**Comment by arabindadora** [comment]
thanks for the tip ❤️
