### ISSUE TITLE
Change warning highlight color

### ISSUE THREAD

**Issue by liketoeatcheese** [bluz71/vim-moonfly-colors#32]
Hey mate,

First of all, love the theme, very pleasing to the eye.

To my question, is there a config somewhere to change the warning or error message color? I'm using MasonLSP if that matters.
![image](https://user-images.githubusercontent.com/88610355/211682226-535003ba-b79d-47d0-8b30-7c8ca40488ff.png)
I'd prefer some more pop up color like red or orange for error so I can pay attention to it.

**Comment by bluz71** [comment]
Refer to the [*Overriding Highlights*](https://github.com/bluz71/vim-moonfly-colors#overriding-highlights) section.

What you want is probably something like this; set this is **before** setting the `colorscheme`:

```lua
local augroup = vim.api.nvim_create_augroup
local autocmd = vim.api.nvim_create_autocmd
local highlight = vim.api.nvim_set_hl

local custom_highlight = augroup("CustomHighlight", {})
autocmd("ColorScheme", {
  pattern = "moonfly",
  callback = function()
    highlight(0, "DiagnosticVirtualTextError", { link = "MoonflyRed" })
    highlight(0, "DiagnosticVirtualTextWarn", { link = "MoonflyYellow" })
    highlight(0, "DiagnosticVirtualTextInfo", { link = "MoonflyBlue" })
    highlight(0, "DiagnosticVirtualTextHint", { link = "MoonflyWhite" })
  end,
  group = custom_highlight,
})
```

**Comment by bluz71** [comment]
A new option now exists to set colored diagnostic virtual text:

```lua
vim.g.moonflyVirtualTextColor = true
```

No workarounds required anymore.
