### ISSUE TITLE
[Question] Should vertsplit be transparent when background is transparent?

### ISSUE THREAD

**Issue by ray-x** [bluz71/vim-moonfly-colors#37]
Different people may have different preferences for split should it be a line or a bar. It looks better as a single line in transparent mode for me. 

Split from moonfly:
<img width="550" alt="image" src="https://user-images.githubusercontent.com/1681295/218614081-9677ae5b-be3a-43ff-bd9e-588725e90f07.png">

reference
<img width="550" alt="image" src="https://user-images.githubusercontent.com/1681295/218614044-4e1a83e4-2911-4869-ba9c-7dd4a75e9308.png">

**Comment by bluz71** [comment]
Split style is controlled by the existing [`moonflyWinSeparator`](https://github.com/bluz71/vim-moonfly-colors#moonflywinseparator) option.

If you want a line just do this:

```lua
vim.g.moonflyWinSeparator = 2
```

If no-separators (aka transparent) are desired then do this:

```lua
vim.g.moonflyWinSeparator = 0
```

The existing option solves the issue, cheers.
