### ISSUE TITLE
Unable to get a transparent background

### ISSUE THREAD

**Issue by SinTan1729** [bluz71/vim-moonfly-colors#41]
I have
```lua
vim.g.moonflyTransparent = true
```
inside my `plugin/moonfly.lua` file but still getting an opaque background.

**Comment by bluz71** [comment]
Sorry for the late response, this issue got lost in my inbox.

Anyway, as far as I can tell, transparency works just fine in Alacritty with Neovim when `vim.g.moonflyTransparent` is set to `true`, as seen in this image:

![moonfly](https://github.com/bluz71/vim-moonfly-colors/assets/11382509/fea5ecbf-463c-4c41-9a65-def8ad96f460)

A couple of things to look for:

- It is best to set `vim.g.moonflyTransparent = true` nice and early, before setting the `colorscheme`
- Test other Neovim themes (such as Tokyo Night) and see whether transparency works or not

From my perspective, transparency does work. You probably have a simple configuration  issue (possibly setting transparency too late, maybe after the theme is loaded).

For now closing this.

**Comment by SinTan1729** [comment]
You're right. Moving `vim.cmd [[colorscheme moonfly]]` to the end of `plugin/moonfly.lua` solved it.

**Comment by bluz71** [comment]
Excellent.
