### ISSUE TITLE
Question: Better highlighter command support for Dockerfile with treesitter, LSP Dockerls

### ISSUE THREAD

**Issue by huyhoang8398** [bluz71/vim-moonfly-colors#43]
![image](https://github.com/bluz71/vim-moonfly-colors/assets/25379882/ac764f22-5804-46bf-80f8-dd27fbf077b8)
Is this possible to highlight these cmd for Dockerfile?
Im using treesitter, lsp dockerls
I think LSP semantic highlighting conflict with treesitter,

Bellow is an example with another colorscheme

![image](https://github.com/bluz71/vim-moonfly-colors/assets/25379882/fa099bf9-8f0c-47ca-a1d9-7ba49aa6d3e5)

**Comment by huyhoang8398** [comment]
Agreed. I will disable LSP semantic highlight for `Dockerfile` and use `Tree-sitter`
![image](https://github.com/bluz71/vim-moonfly-colors/assets/25379882/2b939b75-53b5-4955-a525-500379e6ada2)

`treesitter` is much better
![image](https://github.com/bluz71/vim-moonfly-colors/assets/25379882/7155829c-6e4e-4fc6-babf-f227576c8169)

**Comment by bluz71** [comment]
Agreed, the Dockerfile language server semantic highlights are kind-of awful.

**Comment by huyhoang8398** [comment]
@bluz71 can we re-open this issue?

**Comment by bluz71** [comment]
> I re-open this not sure it due to Treesitter or the colorscheme

I can almost guarantee that is a Tree-sitter issue for Docker filetype. Colorschemes don't control where the styling goes, only what the colors will be. The two lower arrows indicate sections that should be highlighted as `Comment`.

Put your mouse on one of those two lines and run `:lua vim.show_pos()`, what does it say?

Also, what does the same Dockerfile look like when opened with a different colorscheme such as [TokyoNight](https://github.com/folke/tokyonight.nvim)?

For the moment, I don't feel it is correct to re-open this if it is a Tree-sitter issue (which I believe it is).

**Comment by huyhoang8398** [comment]
https://github.com/nvim-treesitter/nvim-treesitter/issues/6975

**Comment by bluz71** [comment]
Yes, confirmed to be an upstream issue.

Best of luck.
