### ISSUE TITLE
Weird background when writting Lua file

### ISSUE THREAD

**Issue by huyhoang8398** [bluz71/vim-moonfly-colors#45]
When Im writing Lua file, the text background becomes black instead of the highlightline color. 
You could see the picture bellow
![image](https://github.com/bluz71/vim-moonfly-colors/assets/25379882/236061a0-77af-4864-90ca-ca2f465206b5)

But when im writting Bash, it doesnt happend
![image](https://github.com/bluz71/vim-moonfly-colors/assets/25379882/3737dca8-dd1f-42d2-9e49-34b125bc27a7)

Do you have any idea?
im using:
- Luals, selene
- bashls, shellcheck

**Comment by bluz71** [comment]
This is going to take me a while to sort out.

I can reproduce the issue.
It relates to `cursorline`; LSP is not the issue.
Other colorschemes don't have this issue.

Currently I don't know why.
But, I will figure it out in time.

**Comment by bluz71** [comment]
I believe I have now fixed this issue.

Please update and let me know if there are any issues.

**Comment by huyhoang8398** [comment]
Work perfect now, thanks
