### ISSUE TITLE
Feat/Questions Request: Changing nvimtree background color

### ISSUE THREAD

**Issue by huyhoang8398** [bluz71/vim-moonfly-colors#47]
<img width="1792" alt="Screenshot 2023-08-06 at 18 19 34" src="https://github.com/bluz71/vim-moonfly-colors/assets/25379882/ef221de5-4de4-4d21-abbe-9cced5983e97">

Im currently using nvimtree floating as the picture above, 
is this possible to change nvimtree background to have something similar to telescope?

**Comment by bluz71** [comment]
Give me a few days, I will get to this.

Query, is this an issue with the latest moonfly version? I did make an NvimTree style change yesterday.

**Comment by huyhoang8398** [comment]
Thanks @bluz71 

Give me a few days, I will get to this.

> Query, is this an issue with the latest moonfly version? I did make an NvimTree style change yesterday.
 
For me i prefer the blue color of the folder, but overwall it's nice

**Comment by bluz71** [comment]
> For me i prefer the blue color of the folder, but overwall it's nice

Does it fix this problem you document in the first post of this issue?

Side note, you can override the icon color change on your side via the following:

```lua
vim.api.nvim_create_autocmd("ColorScheme", {
  pattern = "moonfly",
  callback = function()
    vim.api.nvim_set_hl(0, "NvimTreeFolderIcon", { link = "MoonflyBlue" })
  end,
  group = vim.api.nvim_create_augroup("CustomHighlight", {}),
})
```

Add that code prior to calling `colorscheme moonfly`. Overriding highlights is [documented here](https://github.com/bluz71/vim-moonfly-colors#overriding-highlights).

**Comment by huyhoang8398** [comment]
Im still having grey background for nvimtree, is this possible to make it the same as your showcase picture 
![image](https://github.com/bluz71/vim-moonfly-colors/assets/25379882/68842835-82e0-445b-bb8f-ef08ffd33ec5)

btw override icon folder works well

**Comment by huyhoang8398** [comment]
My bad, it's fine when it is a sidebar,
but not when floating
<img width="1792" alt="Screenshot 2023-08-08 at 23 19 28" src="https://github.com/bluz71/vim-moonfly-colors/assets/25379882/29d0db75-bf0a-49a7-b4cc-51a0dbd3a511">

**Comment by bluz71** [comment]
This should be fixed now in the latest update.

Cheers.

**Comment by huyhoang8398** [comment]
work like a charm , also it just found `moonflyTransparent` is amazing

**Comment by bluz71** [comment]
Glad to hear that.
