### ISSUE TITLE
inlay hint not distinguishable in vim with coc

### ISSUE THREAD

**Issue by jacknicklenson** [bluz71/vim-moonfly-colors#50]
hi,
thx for the colorscheme,
but inlay hint in vim with coc and semantic highlight enabled, is not distinguishable. Here is the side by side comparison (Left Neovim/ Right Vim):

![Screenshot from 2023-10-31 11-55-09](https://github.com/bluz71/vim-moonfly-colors/assets/90291236/ac8327b2-75c1-410f-a927-7e043991ceac)

For Example, in line 201 there is no background color for inlay hint.
Can you make same with the neovim one

Thank you again

**Comment by bluz71** [comment]
I have just committed support for the `CocInlayHint` highlight group. I believe this should address your issue (I think).

Can you update and let me know if your issue has been fixed.

Regards.

**Comment by jacknicklenson** [comment]
it is solved. thank you so much dude. i love u <3
