### ISSUE TITLE
Lualine theme gets overridden

### ISSUE THREAD

**Issue by phaberest** [bluz71/vim-moonfly-colors#52]
I would like to use a darker theme for my lualine whilst using moonfly as my colorscheme, but no matter what I set as lualine theme in its config it keeps showing the moonfly's lualine colors.

In there a global option I can use to disable the override of the lualine theme from moonfly?

**Comment by bluz71** [comment]
I don't use Lualine myself, so I really can't offer much advice.

I do follow the Lualine recommendation of creating an auto-loading theme in moonfly's `lua/lualine/themes` directory. As far as I understand, you should be able to override that using [this Lualine recommendation](https://github.com/nvim-lualine/lualine.nvim#setting-a-theme).

If that does not work, then speak to the Lualine folks. They would be able to clue you into what to do.

Sorry I can't offer anything more concrete.

**Comment by phaberest** [comment]
Thank you @bluz71, I found out what was causing it 🙌🏼 

When installing it using lazy I directly copy-pasted from the readme and thus had `priority = 1000` among parameters, that forced moonfly to always override any theme, lualine included 😅 

Removed that parameter and it just works!

**Comment by bluz71** [comment]
Thanks for the update; worth documenting here if other folks encounter this.

Best regards.
