### ISSUE TITLE
nvim-dap-ui support

### ISSUE THREAD

**Issue by huyhoang8398** [bluz71/vim-moonfly-colors#53]
Hi, I saw that you have support nvim-dap-ui plugin, my current button look like this, is this normal?

![image](https://github.com/bluz71/vim-moonfly-colors/assets/25379882/2417cc95-2f39-41a3-b205-62b329148382)

**Comment by bluz71** [comment]
I don't use `nvim-dap-ui` myself. However, that clearly looks like an issue.

When I have time, soonish, I will endeavour to fix that (give me a couple days).

**Comment by bluz71** [comment]
Control background color for `dap-ui` should now be consistent, I believe this issue has been fixed in the latest commit.

Please update and have a play; if there are still issues let me know (with a screenshot).

I am still a little blind since I don't use `dap-ui` myself.

Best regards.

**Comment by huyhoang8398** [comment]
Thank you for your quick response :-)
it works well now
![image](https://github.com/bluz71/vim-moonfly-colors/assets/25379882/f59d0c24-8ddf-4a5d-90aa-ba7a2a69c7e6)
