### ISSUE TITLE
Not correct colors for git diff

### ISSUE THREAD

**Issue by heyarviind** [bluz71/vim-moonfly-colors#54]
I loved the theme and thank you for the great work. I don't know if I have something misconfigured or it is the default colors but when I open git diff in nvim the colors are just gray. I am expecting it to show green for additions and red for the deletions.

<img width="1007" alt="Screenshot 2024-01-03 at 12 28 18 AM" src="https://github.com/bluz71/vim-moonfly-colors/assets/21043614/25e141b8-fe4e-42df-8db1-0d7b412a8c08">

Is there a way i can update the colors?

**Comment by bluz71** [comment]
That is the intended style, greenish highlights for new line added, and blueish highlights for changes. Deleted lines are intentionally styled as subtle gray.

Why is it this way? The use of muted green & blue allows use of code syntax highlighting in diffs, even for new blocks of code.

I do recommend setting the diff character as some type of leaning slash, as compared to default hyphen, something such as `set fillchars=diff:⁄`.

Here is what my setup looks like, the leaning slashes makes deleted text obvious:

![Diff](https://github.com/bluz71/vim-moonfly-colors/assets/11382509/a86c63dd-c3f2-486c-a6a6-678f9cd737df)

However, if that does not suffice, then you can [override highlights](https://github.com/bluz71/vim-moonfly-colors?tab=readme-ov-file#overriding-highlights) for the `DiffDelete` highlight group per your choice.

Best regards.
