### ISSUE TITLE
React code is not getting highlighting

### ISSUE THREAD

**Issue by heyarviind** [bluz71/vim-moonfly-colors#55]
I am new to Vim and installed Moonfly theme (it looks amazing) but I am not sure why react syntax is not getting highlighted. I am using iTerm2.

<img width="1088" alt="Screenshot 2024-01-05 at 12 31 20 PM" src="https://github.com/bluz71/vim-moonfly-colors/assets/21043614/16b32df4-196a-4fa4-a5f5-6530a3e99032">

**Comment by bluz71** [comment]
JSX highlighting is an editor / plugin responsibility, not a color-scheme issue.

If you are using Vim, then you likely need to install and enable the [vim-jsx-pretty](https://github.com/MaxMEllon/vim-jsx-pretty) plugin.

In Neovim just enable the JavaScript & HTML parsers from Tree-sitter.

This is what I see in my editor:

![JSX](https://github.com/bluz71/vim-moonfly-colors/assets/11382509/e2ea23cd-6acf-4a35-837b-c2f8112e7af1)
