### ISSUE TITLE
Color overriding functionality 

### ISSUE THREAD

**Issue by prashantmaurya19** [bluz71/vim-moonfly-colors#56]
Bro your colorscheme is mind-blowing but I want to override some colors 

I looked you source code but didn't not find 
If there is some way please tell me

**Comment by bluz71** [comment]
It is detailed in the README, [Overriding Highlights](https://github.com/bluz71/vim-moonfly-colors?tab=readme-ov-file#overriding-highlights).

Cheers.

**Comment by prashantmaurya19** [comment]
I now it but I want to override pallet color not any components highlight

For Example red = newred or bright red

**Comment by bluz71** [comment]
Fork the theme in that case and change the colors directly.

Colors are not user overridable apart from forking the entire theme.
