### ISSUE TITLE
Transparent Background Not Working

### ISSUE THREAD

**Issue by cubeDHS2017** [bluz71/vim-moonfly-colors#57]
I rally like this theme but have not been able to enable the transparent background. I have tried setting it using the lua code that was provided. Here is my section of my config that has the colorscheme options.

```
vim.cmd.colorscheme("moonfly")
vim.g.moonflyTransparent = true
```

I do not think I have any plugins that are causing a conflict with this theme. If you need a log of some sort I would be happy to provide it.

**Comment by bluz71** [comment]
Swap the order and try again:

```lua
vim.g.moonflyTransparent = true
vim.cmd.colorscheme("moonfly")
```

**Comment by cubeDHS2017** [comment]
Thank you that fixed the problem.

**Comment by cubeDHS2017** [comment]
I will close this issue now.
