### ISSUE TITLE
Fatal error on install/update

### ISSUE THREAD

**Issue by garbast** [bluz71/vim-moonfly-colors#59]
Using vim-plug in an otherwise empty vim (no other plugins) i get this error on install/update:

```
Updated. Elapsed time: 0.759713 sec.                                                                                   
[x]

- Finishing ... Done!
x moonfly:
    fatal: unknown style 'zdiff3' given for 'merge.conflictstyle'
```

my .vimrc contains:
```
call plug#begin()

Plug 'bluz71/vim-moonfly-colors', { 'as': 'moonfly' }

call plug#end()

colorscheme moonfly
```
I use it on ubuntu with vim version "VIM - Vi IMproved 8.2"

I understand that zdiff3 comes from a git config file. But why does this matter and causes an error. For explanation why i use zdiff3, please see the official documentation https://git-scm.com/docs/git-merge/2.38.0

**Comment by bluz71** [comment]
`vim-plug` uses git under the covers when downloading `moonfly`, same for any other Vim plugin.

Your issue relates to your version of git (too low) and your specified `merge` configuration (likely in your `gitconfig`).

I do not believe this is a problem with this colorscheme. Basically, if you upgrade your version of git I believe this issue would go away.

Best regards.
