### ISSUE TITLE
`mini.notify` support

### ISSUE THREAD

**Issue by tjkuson** [bluz71/vim-moonfly-colors#60]
[`mini.notify`](https://github.com/echasnovski/mini.notify) is a relatively new addition to the `mini` plugin ecosystem that is not currently styled.

Thank you for your work on this project!

**Comment by bluz71** [comment]
Hello @tjkuson,

The _mini.notify_ plugin appears to only use these three highlight groups with default fallback:

- `MiniNotifyBorder` --> `FloatBorder`
- `MiniNotifyNormal` --> `NormalFloat`
- `MiniNotifyTitle` --> `FloatTitle`

I already style `FloatBorder` and `NormalFloat`, but not `FloatTitle`. 

Don't forget the [`moonflyNormalFloat`](https://github.com/bluz71/vim-moonfly-colors#moonflynormalfloat) can be used to change the background color of floats, I always set it to true for a black background color in floats.

Anyway, I have now added in a style for `FloatTitle` which was the only one I had not already styled.

I assume that should be enough, however, I am confused when you say _not currently styled_. The _mini.notify_ plugin mostly is using default highlight groups which moonfly had already styled.

For now I am closing. If there is an issue, please post a screenshot with code snippet for me to reproduce.

Best regards.

**Comment by tjkuson** [comment]
Thank you for the quick response and pointers!

> I assume that should be enough, however, I am confused when you say not currently styled. The mini.notify plugin mostly is using default highlight groups which moonfly had already styled.

Yes, this is what I meant. I worded myself poorly, apologies.
