### ISSUE TITLE
Treesitter context is not distinguishable with moonflyNormalFloat enabled

### ISSUE THREAD

**Issue by tjkuson** [bluz71/vim-moonfly-colors#62]
Hello!

When moonflyNormalFloat is enabled, the [Treesitter context](https://github.com/nvim-treesitter/nvim-treesitter-context) is not visually separate from normal text. One solution would be to use a repeated character to separate the context from the rest of the buffer. However, this displaces the text vertically and looks ugly when switching to a different theme (e.g., a light one).

Thanks again for maintaining this project!

## Reproduction

Below is a reproduction in case you find it helpful.

```lua
local plugins = {
	ts = "https://github.com/nvim-treesitter/nvim-treesitter",
	ts_context = "https://github.com/nvim-treesitter/nvim-treesitter-context",
	moonfly = "https://github.com/bluz71/vim-moonfly-colors",
	catppuccin = "https://github.com/catppuccin/nvim",
}

for name, url in pairs(plugins) do
	local install_path = "/tmp/nvim/site/" .. name
	if vim.fn.isdirectory(install_path) == 0 then
		vim.fn.system({ "git", "clone", "--depth=1", url, install_path })
	end
	vim.o.runtimepath = install_path .. "," .. vim.o.runtimepath
end

vim.g.moonflyNormalFloat = true
vim.cmd([[colorscheme moonfly]])
```

and then `nvim --clean -u minimal.lua` into a file with appropriately large structures.

For example, in

<img width="397" alt="Screenshot 2024-06-24 at 10 01 26" src="https://github.com/bluz71/vim-moonfly-colors/assets/12143269/922c5fb1-db53-4f60-96bb-9dd2fe3dc6a7">

the function body looks incorrect upon first inspection. This problem is worse when there are multiple contexts (e.g., a loop in a function in a class).

Adding `require("treesitter-context").setup({ separator = "━" })` to `minimal.lua` adds a helpful separator. However, here is what it looks like with `vim.cmd([[colorscheme catppuccin-latte]])`.

<img width="397" alt="Screenshot 2024-06-24 at 10 06 54" src="https://github.com/bluz71/vim-moonfly-colors/assets/12143269/dac35055-c1a1-499c-9485-0ecde64a8df0">

As you can see, it duplicates catppuccin's line and looks quite distracting.

**Comment by bluz71** [comment]
Thanks for bringing this to my attention.

Please update, I believe this is now much improved.

I have copied the `catppuccin` approach with a subtle underline, and I have also slightly changed the background of the context area to make it more obvious.

Let me know if you have any issues.

**Comment by tjkuson** [comment]
I just updated and it looks great. Thank you!
