### ISSUE TITLE
wezterm colorscheme bright yellow

### ISSUE THREAD

**Issue by Yetso** [bluz71/vim-moonfly-colors#65]
Hello, 

I notice the bright yellow (khaki) color isn't right for the wezterm color theme (moonfly-wezterm.toml).

it's #c2c292 when it's supposed to be ﻿#c6c684 (line 37)

Love the theme btw.

Thanks

**Comment by bluz71** [comment]
Thanks for fixing this.

Indeed I did change _khaki_ (yellow for strings) earlier this year (more contrast) and this instance was not corrected.

I appreciate the assistance.

Side note, I don't know what has happened, but in the last two weeks or so moonfly has gained quite a few more GitHub stars. Interesting.

Best regards.
